export type Category = { id: number; slug: string; nume: string; display_count: number; art: string; ordine: number };
export type Vehicle  = { id: number; slug: string; nume: string; an: number | null; vin_masca: string | null; piese_listate: number; intrare: string };
export type Product  = {
  id: number; slug: string; nume: string; oem: string; stare: "A" | "B" | "C";
  stare_nota: string | null; pret_lei: number; pret_sufix: string | null; ani: string | null;
  art: string; categorie_id: number | null; vehicul_id: number | null;
  compat: string[]; stoc: number; publicat: boolean; model_ids?: number[]; greutate_kg?: number | null; cost_lei?: number | null; vizualizari?: number;
  categories?: Category | null; vehicles?: Vehicle | null;
};
export type CartItem = { id: number; slug: string; nume: string; pret: number; art: string; oem: string; cantitate: number };
export type Brand = { id: number; slug: string; nume: string; ordine: number };
export type Model = { id: number; brand_id: number; slug: string; nume: string };
export type OrderEvent = { id: number; order_id: number; tip: string; mesaj: string; autor: string; created_at: string };
export type OrderFull = { id: number; numar: string; tip_client: string; nume: string; email: string; telefon: string;
  firma: string | null; cui: string | null; adresa: string; oras: string; judet: string; curier: string; plata: string;
  subtotal: number; livrare: number; total: number; status: string; gdpr: boolean; created_at: string;
  awb: string | null; nota_interna: string | null; factura_serie: string | null; factura_status: string;
  discount_cod: string | null; discount_valoare: number };
export type Discount = { id: number; cod: string; tip: "procent" | "fix"; valoare: number;
  minim_comanda: number; expira_la: string | null; activ: boolean; folosiri: number };
export type VehiculAdmin = { id: number; slug: string; nume: string; an: number | null; vin_masca: string | null;
  piese_listate: number; intrare: string; cost_achizitie: number | null; status: string };
